theme: jekyll-theme-minimal # You can remove this line if you don't want any default Jekyll theme styling interfering.
title: Cole Feuer - Software Developer & ML Researcher
description: Personal website of Cole Feuer, showcasing projects, experience, and skills in AI and software development.
